version: "3.1"

services:
    online-voting:
        image: ieeeuottawa/online-voting
        ports:
          - "8080:8080"
        depends_on:
          - online-voting-db
          - online-voting-server
        links:
          - online-voting-db
          - online-voting-server
    online-voting-db:
        image: postgres:11
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER_FILE=/run/secrets/db_user
          - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
          - POSTGRES_DB_FILE=/run/secrets/db_name
        volumes:
          - /var/lib/postgresql/data:/var/lib/postgresql/data
        secrets:
          - db_user
          - db_password
          - db_name
    online-voting-server:
        image: nginx:alpine
        restart: on-failure
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./cloudflare.pem:/etc/nginx/cloudflare.pem
          - ./cloudflare.key:/etc/nginx/cloudflare.key
        ports:
          - 80:80
          - 443:443

secrets:
  db_user:
    file: ./secrets/db_user.secret
  db_password:
    file: ./secrets/db_password.secret
  db_name:
    file: ./secrets/db_name.secret